### ISSUE TITLE
Config Read Errors in Regards to Profiles

### ISSUE THREAD

**Issue by casrep** [CenturyLinkCloud/clc-go-cli#58]
When trying to log in with a profile, I get the error below. I'm assuming the tool is expecting some kind of delimitation in the config somewhere.

```
$ clc login --profile p1
Failed to load config file, error: yaml: line 5: did not find expected ',' or '}'
```

What is the correct way to have the profiles added? Your documentation doesn't mention the braces, so are they required? When I remove the braces and try again, I get this error.

```
$ clc login --profile p1
Failed to load config file, error: yaml: line 4: found character that cannot start any token
```

Here's my config.yml.

```
user: username1
password: password1
defaultformat: text
profiles: {
  p1:
    user: username2
    password: password2
  p2:
    user: username3
    password: password3
}
defaultdatacenter: IL1
```

**Comment by chrislittle** [comment]
your config.yml should look like this.

```
user: mydefaultusername
password: mydefaultpassowrd
defaultformat: json
profiles:
  demo:
    user: myusername
    password: mypassword
  sandbox:
    user: myusername
    password: mypassword
  internaluse:
    user: myusername
    password: mypassword
defaultdatacenter: ""
```

this gives me 4 profiles to use.  
1.  my default profile, any query will be executed using this information.  no need to even use the clc login if this is set in your yml.  
```
clc server list --all
```
this lists all VM's in my default profile
2. 3 other profiles for demo, sandbox, internaluse i can call anytime.  for example (again no need to use clc login ever if you have this set in the yml)
```
clc server list --all --profile demo
```
that lists everything in my account that is linked to demo userID

**Comment by casrep** [comment]
I've updated the profile by removing the braces. I'm still getting the error below, though.

```
$ clc server list --all --profile p1
Failed to load config file, error: yaml: line 4: found character that cannot start any token
```

config

```
user: username1
password: password1
defaultformat: text
profiles: 
  p1:
    user: username2
    password: password2
  p1:
    user: username3
    password: password3
defaultdatacenter: ""
```
